# Generated by Django 4.0.4 on 2022-05-19 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime_id', models.IntegerField(verbose_name='anime_id')),
                ('type', models.CharField(max_length=10, verbose_name='type')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('synopsis', models.CharField(max_length=99999, verbose_name='synopsis')),
                ('episodes', models.IntegerField(verbose_name='episodes')),
                ('score', models.FloatField(max_length=3, verbose_name='score')),
                ('scored_by', models.IntegerField(verbose_name='scored_by')),
                ('rank', models.IntegerField(verbose_name='rank')),
                ('popularity', models.IntegerField(verbose_name='popularity')),
                ('url', models.CharField(max_length=100, verbose_name='url')),
            ],
        ),
    ]
